version: '3.5'

services:

  nats:
    image: local/nats-streaming
    build:
      context: ./backend/nats-streaming
    hostname: nats
#    ports:
#      - "4222:4222"
#      - "6222:6222"
#      - "8222:8222"
    env_file:
      - ./backend/nats-streaming/.env
  
